AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Creates a least-privilege application deployment role that explicitly trusts the central tooling role ARN.
  This template is deployed automatically by the 'onboard-environment.yml' workflow.

Parameters:
  ToolingRoleArn:
    Type: String
    Description: "The full ARN of the central CI/CD tooling role. This is provided automatically by the onboarding workflow."
  TargetRoleName:
    Type: String
    Default: "InternalToolingDeploymentRole"
    Description: "The static name of the application deployment role being created. This value should not be changed."

Resources:
  InternalToolingDeploymentRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Ref TargetRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref ToolingRoleArn
            Action: "sts:AssumeRole"
      Policies:
        # This policy grants all necessary permissions for a typical serverless application.
        # It can be customized or replaced as needed for different types of applications.
        - PolicyName: "GenericApplicationDeploymentPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "s3:GetObject"
                Resource: "arn:aws:s3:::*/*"
              - Effect: Allow
                Action:
                  - "iam:GetRole"
                  - "iam:CreateRole"
                  - "iam:DeleteRole"
                  - "iam:PutRolePolicy"
                  - "iam:DeleteRolePolicy"
                  - "iam:PassRole"
                Resource: "arn:aws:iam::*:role/*"
              - Effect: Allow
                Action:
                  - "lambda:*"
                  - "events:*"
                  - "cloudwatch:*"
                  - "tag:GetResources"
                  - "ec2:DescribeInstances"
                Resource: "*"

Outputs:
  InternalToolingDeploymentRoleArn:
    Description: >-
      FOR INFORMATION: This is the ARN of the created application deployment role.
      The onboarding workflow automatically captures this and creates an SSM parameter with its value.
    Value: !GetAtt InternalToolingDeploymentRole.Arn
