AWSTemplateFormatVersion: "2010-09-09"
Description: >
  MANAGEMENT CONNECTOR: Deploys a permanent IAM Role in a target account that acts as a secure
  entry point for GitHub Actions to perform high-level management tasks.

Parameters:
  # Your GitHub organization name (e.g., 'esbpcs-org').
  GitHubOrg:
    Type: String
    Description: "Your GitHub organization name (e.g., 'esbpcs-org')."

  # The name of your central management repository where reusable workflows reside.
  GitHubRepo:
    Type: String
    Description: "The name of your central management repository where your reusable workflows reside."
    Default: "CentralManagementRepo"

  # A unique base name for the resources in this stack.
  ProjectName:
    Type: String
    Description: "A unique base name for the resources in this stack."
    Default: "GitHub-Management-Connector"

Resources:
  # This resource creates the OIDC identity provider for GitHub Actions.
  # It establishes a trust relationship between your AWS account and GitHub.
  GitHubOIDCProvider:
    Type: "AWS::IAM::OIDCProvider"
    Properties:
      Url: "https://token.actions.githubusercontent.com"
      ClientIdList: ["sts.amazonaws.com"]

  # This is the management connector role that will be assumed by GitHub Actions.
  # It has permissions to manage CloudFormation stacks and IAM roles in the target account.
  ManagementConnectorRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Ref ProjectName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref GitHubOIDCProvider
            Action: "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
              StringLike:
                "token.actions.githubusercontent.com:sub": !Sub "repo:${GitHubOrg}/${GitHubRepo}:*"
      Policies:
        - PolicyName: "ManagementConnectorPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "cloudformation:CreateStack"
                  - "cloudformation:DescribeStacks"
                  - "cloudformation:UpdateStack"
                  - "cloudformation:DeleteStack"
                  - "cloudformation:CreateChangeSet"
                  - "cloudformation:ExecuteChangeSet"
                  - "cloudformation:DeleteChangeSet"
                  - "cloudformation:DescribeChangeSet"
                  - "cloudformation:GetTemplate"
                  - "cloudformation:GetTemplateSummary"
                  - "cloudformation:DescribeStackEvents"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:CreateBucket"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "iam:CreateRole"
                  - "iam:GetRole"
                  - "iam:DeleteRole"
                  - "iam:PutRolePolicy"
                  - "iam:DeleteRolePolicy"
                  - "iam:PassRole"
                Resource: "arn:aws:iam::*:role/InternalToolingDeploymentRole"
Outputs:
  # The ARN of the created management connector role.
  # This value needs to be saved as a secret in your GitHub environment.
  ManagementConnectorRoleArn:
    Description: >-
      ACTION REQUIRED: Copy this ARN. In your GitHub repository, create a GitHub Environment
      (e.g., 'esbpcs-sandbox') and save this ARN as an environment-specific secret.
      The required secret name is 'MANAGEMENT_CONNECTOR_ROLE_ARN'.
    Value: !GetAtt ManagementConnectorRole.Arn
