AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Deploys the central, one-time resources for GitHub Actions OIDC integration. This includes the OIDC Provider and a central Tooling Role for your entire organization.

Parameters:
  GitHubOrg:
    Type: String
    Description: "Your GitHub organization name (e.g., 'esbpcs-org')."
  GitHubRepo:
    Type: String
    Description: "The name of your central management repository where your reusable workflows reside."
    Default: "CentralManagementRepo"
  ProjectName:
    Type: String
    Description: "A unique base name for resources created by this stack (e.g., the name of your organization or primary project)."
    Default: "ESBPCS"
  TargetRoleName:
    Type: String
    Description: "The static name of the application deployment role created in target accounts. This value should not be changed."
    Default: "InternalToolingDeploymentRole"
  SsmParameterPath:
    Type: String
    Description: "The root path in SSM Parameter Store for storing all project role ARNs. This value should not be changed."
    Default: "/github/"

Resources:
  GitHubOIDCProvider:
    Type: "AWS::IAM::OIDCProvider"
    Properties:
      Url: "https://token.actions.githubusercontent.com"
      ClientIdList: ["sts.amazonaws.com"]

  GitHubActionsToolingRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${ProjectName}-GitHubActionsToolingRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref GitHubOIDCProvider
            Action: "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
              StringLike:
                "token.actions.githubusercontent.com:sub": !Sub "repo:${GitHubOrg}/${GitHubRepo}:*"
      Policies:
        - PolicyName: "AssumeDeploymentRolesAndReadConfigPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "sts:AssumeRole"
                Resource: !Sub "arn:aws:iam::*:role/${TargetRoleName}"
              - Effect: Allow
                Action: "ssm:GetParameter"
                Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${SsmParameterPath}*"
              - Effect: Allow
                Action: "kms:Decrypt"
                Resource: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/*"

Outputs:
  GitHubActionsToolingRoleArn:
    Description: >-
      ACTION REQUIRED: Copy this ARN and save it as a repository-level secret in your central management
      GitHub repository. The required secret name is 'TOOLING_ACCOUNT_OIDC_ROLE_ARN'.
    Value: !GetAtt GitHubActionsToolingRole.Arn
    Export:
      Name: !Sub "${ProjectName}-ToolingRoleArn"
