AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Deploys the central, one-time resources for GitHub Actions OIDC integration. This includes the OIDC Provider and a central Tooling Role for your entire organization.

Parameters:
  # Your GitHub organization name (e.g., 'esbpcs-org').
  GitHubOrg:
    Type: String
    Description: "Your GitHub organization name (e.g., 'esbpcs-org')."

  # The name of your central management repository where reusable workflows reside.
  GitHubRepo:
    Type: String
    Description: "The name of your central management repository where your reusable workflows reside."
    Default: "CentralManagementRepo"

  # A unique base name for resources created by this stack.
  ProjectName:
    Type: String
    Description: "A unique base name for resources created by this stack (e.g., the name of your organization or primary project)."
    Default: "ESBPCS"

  # The static name of the application deployment role created in target accounts.
  TargetRoleName:
    Type: String
    Description: "The static name of the application deployment role created in target accounts. This value should not be changed."
    Default: "InternalToolingDeploymentRole"

  # The root path in SSM Parameter Store for storing role ARNs.
  SsmParameterPath:
    Type: String
    Description: "The root path in SSM Parameter Store for storing all project role ARNs. This value should not be changed."
    Default: "/github/"

Resources:
  # This resource creates the OIDC identity provider for GitHub Actions.
  # It establishes a trust relationship between your AWS account and GitHub.
  GitHubOIDCProvider:
    Type: "AWS::IAM::OIDCProvider"
    Properties:
      Url: "https://token.actions.githubusercontent.com"
      ClientIdList: ["sts.amazonaws.com"]

  # This is the central tooling role that will be assumed by GitHub Actions.
  # It has permissions to assume deployment roles in other accounts and read configuration from SSM.
  GitHubActionsToolingRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${ProjectName}-GitHubActionsToolingRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref GitHubOIDCProvider
            Action: "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
              StringLike:
                "token.actions.githubusercontent.com:sub": !Sub "repo:${GitHubOrg}/${GitHubRepo}:*"
      Policies:
        - PolicyName: "AssumeDeploymentRolesAndReadWriteConfigPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "sts:AssumeRole"
                Resource: !Sub "arn:aws:iam::*:role/${TargetRoleName}"
              - Effect: Allow
                Action:
                  - "ssm:GetParameter"
                  - "ssm:PutParameter"
                  - "ssm:DeleteParameter"
                Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${SsmParameterPath}*"
              - Effect: Allow
                Action: "kms:Decrypt"
                Resource: "*"

Outputs:
  # The ARN of the created tooling role.
  # This value needs to be saved as a secret in your GitHub repository.
  GitHubActionsToolingRoleArn:
    Description: >-
      ACTION REQUIRED: Copy this ARN and save it as a repository-level secret in your central management
      GitHub repository. The required secret name is 'TOOLING_ACCOUNT_OIDC_ROLE_ARN'.
    Value: !GetAtt GitHubActionsToolingRole.Arn
    Export:
      Name: !Sub "${ProjectName}-ToolingRoleArn"
